name: My Test WorkFlow #Name of the workflow

on: [push] #Trigger for the Workflow

jobs: #Jobs section starts here
  say-hello: # Job Name
    runs-on: ubuntu-latest # Runner name
    steps:
      - name: Print Greeting # name of each step
        run: echo "Hello, Rahul!"
